/* Browser presentation on top of the replaceable local repository. */
(() => {
  'use strict';
  const C=window.RunSport;
  let storage;try{storage=window.localStorage;}catch{storage={getItem(){throw Error('Stockage indisponible');},setItem(){throw Error('Stockage indisponible');},removeItem(){throw Error('Stockage indisponible');}};}
  const store=C.createStore(storage);
  const $=s=>document.querySelector(s);
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=s=>Number.isFinite(C.day(s))?new Date(s+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'short',day:'numeric',month:'short',year:'numeric'}):'Date non renseignée';
  const formData=form=>{const data=new FormData(form),values=Object.fromEntries(data);if(form.querySelector('[name=trainingDays]'))values.trainingDays=data.getAll('trainingDays');return values;};
  function feedback(id,text,error=false){const el=document.getElementById(id);if(!el)return;el.hidden=!text;el.textContent=text;el.classList.toggle('error',error);}
  function safe(fn,id){try{fn();}catch(error){feedback(id,error.message,true);if(id==='plan-feedback')renderPlan();}}
  function empty(text){return `<div class="sport-empty">${esc(text)}</div>`;}
  function savedMessage(){return 'Enregistré sur cet appareil uniquement.';}
  function fill(form,values){if(!form||!values)return;for(const [key,value]of Object.entries(values)){const f=form.elements.namedItem(key);if(f&&'value'in f&&f.type!=='checkbox')f.value=value??'';}}
  function sourceLink(source){return /^https:\/\/www\.openstreetmap\.org\/(node|way|relation)\/\d+$/.test(source||'')?source:null;}
  function favorite(place,kind='place'){
    store.update(s=>{if(!s.favorites.some(f=>f.id===place.id&&f.kind===kind))s.favorites.push({...place,kind,createdAt:new Date().toISOString()});});
  }
  window.SportUI={C,store,esc,date,feedback,favorite,sourceLink};
  store.read();feedback('storage-warning',store.issue,true);
  window.addEventListener('storage',event=>{if(event.key===store.key)feedback('storage-warning','Les données de cet espace ont changé dans un autre onglet. Recharge cette page pour actualiser l’affichage.',true);});

  function renderGoals(){const el=$('#goal-list');if(!el)return;const s=store.read();el.innerHTML=s.goals.length?s.goals.map(g=>`<article class="sport-list-item"><h3>${esc(g.title)}</h3><p>${esc(C.sports[g.sport]||g.sport)} · ${date(g.date)}${g.distance?` · ${esc(g.distance)} km`:''}</p>${g.planId===s.plan?.id?'<a class="sport-link" href="mon-plan.html">Voir le plan actif →</a>':`<button type="button" class="sport-link" data-delete-goal="${esc(g.id)}">Retirer cet objectif</button>`}</article>`).join(''):empty('Aucun objectif enregistré. Commence par une envie de sortie ou le questionnaire.');}
  function renderFavorites(){const el=$('#favorite-list');if(!el)return;const favorites=store.read().favorites;el.innerHTML=favorites.length?favorites.map(f=>`<article class="sport-list-item"><span class="sport-tag">${f.kind==='route'?'Parcours piéton':'Lieu repéré · non partenaire'}</span><h3>${esc(f.name)}</h3>${f.kind==='route'?`<p>${esc(Number(f.kilometers).toFixed(2))} km · tracé piéton enregistré</p><a class="sport-link" href="index.html?route=${encodeURIComponent(f.id)}">Ouvrir le parcours →</a>`:`<p>${esc(f.address||'')}</p>${sourceLink(f.source)?`<a href="${esc(f.source)}" target="_blank" rel="noreferrer">Voir la source OpenStreetMap ↗</a>`:''}`}<div><button class="sport-link" type="button" data-delete-favorite="${esc(f.id)}">Retirer le favori</button></div></article>`).join(''):empty('Aucun lieu ou parcours enregistré sur cet appareil.');
    const select=$('#activity-form [name=routeId]');if(select){const value=select.value;select.innerHTML='<option value="">Aucun parcours associé</option>'+favorites.filter(f=>f.kind==='route').map(f=>`<option value="${esc(f.id)}">${esc(f.name)}</option>`).join('');select.value=value;}}
  function renderActivities(){const el=$('#activity-list');if(!el)return;const all=store.read().activities;el.innerHTML=all.length?[...all].sort((a,b)=>b.date.localeCompare(a.date)).map(a=>{const pace=a.sport==='running'&&a.distance>0?`${Math.floor(Math.round(a.duration*60/a.distance)/60)}:${String(Math.round(a.duration*60/a.distance)%60).padStart(2,'0')} min/km`:' ';return `<article class="sport-list-item"><span class="sport-tag">Saisie manuelle</span><h3>${esc(C.sports[a.sport])} · ${date(a.date)}</h3><p>${esc(a.duration)} min${a.distance!=null?` · ${esc(a.distance)} km`:''}${a.elevation!=null?` · D+ ${esc(a.elevation)} m`:''} ${esc(pace)}</p>${a.notes?`<p>${esc(a.notes)}</p>`:''}<div class="sport-actions"><a class="sport-link" href="apres-sortie.html?activity=${encodeURIComponent(a.id)}">Après cette sortie →</a><button class="sport-link" type="button" data-delete-activity="${esc(a.id)}">Supprimer cette saisie</button></div></article>`;}).join(''):empty('Aucune sortie enregistrée. Les compteurs restent à zéro tant que tu n’as rien saisi.');}
  function challengeCard(c,activities){const value=C.challengeProgress(c,activities),percent=Math.min(100,Math.round(value/c.target*100));return `<article class="sport-list-item"><span class="sport-tag">Défi personnel · local</span><h3>${esc(c.title)}</h3><p>Du ${date(c.startDate)} au ${date(c.endDate)}</p><progress max="100" value="${percent}" aria-label="Progression ${esc(c.title)}"></progress><p>${value} / ${c.target} ${c.unit==='km'?'km':'sorties'} déclarés · ${percent}%</p><button class="sport-link" type="button" data-delete-challenge="${esc(c.id)}">Retirer ce défi</button></article>`;}
  function renderChallenges(){const s=store.read();for(const id of ['challenge-list','dashboard-challenges']){const el=document.getElementById(id);if(el)el.innerHTML=s.challenges.length?s.challenges.map(c=>challengeCard(c,s.activities)).join(''):empty('Aucun défi personnel choisi.');}
    const el=$('#challenge-options');if(el)el.innerHTML=C.templates.map(t=>`<article class="sport-card"><h3>${esc(t.title)}</h3><p>À partir des sorties saisies ce mois-ci. Aucun classement ni cadeau associé.</p><button type="button" class="button" data-challenge="${t.id}">Choisir ce défi</button></article>`).join('');}
  function renderDashboard(){const el=$('#dashboard-summary');if(!el)return;const s=store.read();let p=s.plan?C.progress(s.plan):null;el.innerHTML=`<section class="sport-card dark"><p class="eyebrow">${s.profile?.alias?'BONJOUR '+esc(s.profile.alias):'TON PROCHAIN RENDEZ-VOUS AVEC TOI'}</p><h2>${s.plan?esc(C.objectives[s.plan.objective].label):'Un objectif, puis un premier pas.'}</h2>${p?`<p>Semaine ${p.current} / ${s.plan.duration} · ${p.completed} séance(s) déclarée(s) réalisée(s)</p><progress max="100" value="${p.percent}" aria-label="Progression du plan"></progress><p>${p.percent}% des séances cochées</p><a class="button lime" href="mon-plan.html">Ouvrir mon plan →</a>`:'<p>Crée ton programme à partir de ta pratique et de tes disponibilités.</p><a class="button lime" href="questionnaire.html">Définir mon objectif →</a>'}</section><div class="sport-stats"><div><strong>${s.activities.length}</strong><span>sorties saisies</span></div><div><strong>${Math.round(s.activities.reduce((n,a)=>n+(a.distance||0),0)*10)/10}</strong><span>km déclarés · tous sports</span></div><div><strong>${s.favorites.length}</strong><span>lieux et parcours favoris</span></div></div>`;}
  function lists(){renderDashboard();renderGoals();renderFavorites();renderActivities();renderChallenges();}
  const profileForm=$('#profile-form');
  if(profileForm){const p=store.read().profile;fill(profileForm,p);for(const input of profileForm.querySelectorAll('[name=sports]'))input.checked=!!p?.sports?.includes(input.value);profileForm.addEventListener('submit',event=>{event.preventDefault();safe(()=>{const values=formData(profileForm);store.update(s=>{s.profile={...s.profile,alias:values.alias.trim().slice(0,40),sport:values.sport,level:values.level,sessions:Number(values.sessions),sports:[...new Set([values.sport,...new FormData(profileForm).getAll('sports')])],preferences:values.preferences.slice(0,200)};});feedback('profile-feedback',savedMessage()+' Le plan actif reste inchangé : recommence le questionnaire pour l’adapter.');renderDashboard();},'profile-feedback');});}
  const goalForm=$('#goal-form');if(goalForm)goalForm.addEventListener('submit',event=>{event.preventDefault();safe(()=>{const v=formData(goalForm);if(!v.title.trim()||!Number.isFinite(C.day(v.date))||C.day(v.date)<C.day(C.today()))throw Error('Indique un titre et une date aujourd’hui ou dans le futur.');store.update(s=>s.goals.push({id:C.uid(),userId:'local-device',title:v.title.trim(),sport:v.sport,date:v.date,distance:v.distance?Number(v.distance):null}));goalForm.reset();renderGoals();feedback('goal-feedback',savedMessage());},'goal-feedback');});
  let linkedWorkoutId=new URLSearchParams(location.search).get('workout');
  const activityForm=$('#activity-form');if(activityForm){activityForm.elements.date.value=C.today();activityForm.elements.date.max=C.today();const workout=store.read().plan?.weeks.flatMap(w=>w.workouts).find(w=>w.id===linkedWorkoutId);if(workout){feedback('linked-workout','Cette saisie sera liée à ta séance prévue le '+date(workout.date)+'. Indique les mesures réellement effectuées.');const previous=store.read().activities.find(a=>a.workoutId===linkedWorkoutId);if(previous)fill(activityForm,previous);}else linkedWorkoutId=null;
    activityForm.addEventListener('submit',event=>{event.preventDefault();safe(()=>{const a=C.cleanActivity({...formData(activityForm),workoutId:linkedWorkoutId});if(linkedWorkoutId&&a.sport!==store.read().plan?.sport)throw Error('Le sport de cette sortie doit correspondre à la séance liée. Utilise une saisie libre pour un autre sport.');store.update(s=>{const previous=s.activities.find(x=>linkedWorkoutId&&x.workoutId===linkedWorkoutId);if(previous){a.id=previous.id;s.activities=s.activities.map(x=>x.id===a.id?a:x);}else s.activities.push(a);const w=s.plan?.weeks.flatMap(w=>w.workouts).find(w=>w.id===linkedWorkoutId);if(w){w.completed=true;w.completedAt=a.date;}});activityForm.reset();activityForm.elements.date.value=C.today();linkedWorkoutId=null;feedback('linked-workout','');feedback('activity-feedback','Sortie enregistrée sur cet appareil. Les défis personnels ont été actualisés.');lists();},'activity-feedback');});}
  function renderPlan(){const el=$('#active-plan');if(!el)return;const p=store.read().plan;if(!p){el.innerHTML=empty('Aucun plan actif sur cet appareil.')+'<a class="button lime" href="questionnaire.html">Créer mon plan →</a><p><a class="sport-link" href="plans-entrainement.html">Consulter les huit PDF gratuits</a></p>';return;}
    const stats=C.progress(p);const next=stats.next;const nextText=next?`${date(next.date)} · ${next.type==='event'?'Objectif course':next.duration+' min · '+({easy:'Footing facile',long:'Endurance',varied:'Variations contrôlées'}[next.type])}`:'Aucune séance future restante.';
    el.innerHTML=`<section class="sport-card dark"><p class="eyebrow">${esc(C.objectives[p.objective].label)}</p><h2>Ta préparation, à ton rythme.</h2><p>Objectif le ${date(p.targetDate)}${p.targetMinutes?' · souhait : '+esc(p.targetMinutes)+' min':''} · ${p.sessionsPerWeek} séances maximum / semaine</p><p>Du ${date(p.startDate)} au ${date(p.targetDate)} · ${p.duration} semaines</p><progress max="100" value="${stats.percent}" aria-label="Séances réalisées"></progress><p>${stats.percent}% · ${stats.completed} / ${stats.total} séances déclarées réalisées</p></section><div class="sport-stats"><div><strong>${stats.current}/${p.duration}</strong><span>semaine au calendrier</span></div><div><strong>${stats.currentDone}</strong><span>séances cochées cette semaine</span></div><div><strong>${stats.currentRemaining}</strong><span>restantes cette semaine</span></div></div><section class="sport-card"><p class="eyebrow">PROCHAINE SÉANCE</p><h2>${esc(nextText)}</h2>${next?`<p>${esc(next.description)}</p><a class="button lime" href="#week-${next.week}">Voir la séance →</a>`:''}<p>${stats.overdue?stats.overdue+' séance(s) passée(s) non cochée(s). Ne les cumule pas pour rattraper.':''}</p><div class="sport-actions"><a class="sport-link" href="questionnaire.html">Modifier mon objectif / recommencer</a><a class="sport-link" href="compte-sportif.html#sorties">Saisir une sortie réelle</a><a class="sport-link" href="apres-sortie.html">Après ma sortie →</a></div><details><summary>Pourquoi ce programme ?</summary>${p.notes.map(n=>`<p>${esc(n)}</p>`).join('')}<p>Le modèle ne s’adapte pas automatiquement à tes sensations. Les séances sont générales et doivent rester confortables pour toi.</p></details></section>${p.weeks.map(w=>`<details class="sport-week" id="week-${w.number}" ${w.number===stats.current?'open':''}><summary>Semaine ${w.number} · ${date(w.workouts[0].date)} <span class="sport-tag ${w.kind==='recovery'?'recovery':''}">${({build:'Progression',recovery:'Allègement',taper:'Avant l’objectif',event:'Semaine objectif'})[w.kind]}</span> ${w.workouts.filter(x=>x.completed).length}/${w.workouts.length} réalisées</summary>${w.workouts.map((x,i)=>`<article class="workout ${x.type}"><p class="eyebrow">${date(x.date)} · SÉANCE ${i+1}</p><h3>${x.type==='event'?'Objectif '+x.distance+' km':x.duration+' min · '+({easy:'Footing facile',long:'Endurance',varied:'Variations contrôlées'}[x.type])}</h3><p>${esc(x.description)}</p><label class="check-row completed-label"><input type="checkbox" data-workout="${esc(x.id)}" ${x.completed?'checked':''}>Séance réalisée${x.completedAt?' · déclarée le '+date(x.completedAt):''}</label><a class="sport-link" href="compte-sportif.html?workout=${encodeURIComponent(x.id)}#sorties">Saisir ma sortie réelle →</a></article>`).join('')}</details>`).join('')}`;
  }
  document.addEventListener('change',event=>{const id=event.target.dataset.workout;if(id)safe(()=>{const open=[...document.querySelectorAll('.sport-week[open]')].map(el=>el.id);store.update(s=>{const w=s.plan?.weeks.flatMap(w=>w.workouts).find(x=>x.id===id);if(!w)throw Error('Cette séance n’existe plus. Recharge la page.');w.completed=event.target.checked;w.completedAt=w.completed?C.today():null;});renderPlan();for(const key of open){const el=document.getElementById(key);if(el)el.open=true;}feedback('plan-feedback','Progression enregistrée localement. Pour tes distances et tes défis, saisis la sortie réelle.');},'plan-feedback');});
  function renderEvents(){const el=$('#event-list');if(!el)return;const list=store.read().eventDrafts;el.innerHTML=list.length?list.map(v=>`<article class="sport-list-item"><span class="sport-tag planned">Brouillon · non publié</span><h3>${esc(v.title)}</h3><p>${esc(C.sports[v.sport])} · ${esc(v.distance)} km · ${date(v.date)} à ${esc(v.time)}</p><p>${esc(v.location)} · niveau ${esc({all:'tous niveaux',beginner:'débutant',regular:'régulier',experienced:'expérimenté'}[v.level])}</p><p>Capacité envisagée : ${v.maxParticipants} personnes. Aucune inscription ni place réservée.</p><p>${esc(v.description)}</p><button class="button unavailable" type="button" disabled>Publication disponible avec les comptes</button><div><button class="sport-link" type="button" data-delete-event="${esc(v.id)}">Supprimer ce brouillon</button></div></article>`).join(''):empty('Aucun brouillon enregistré. Aucun événement public n’est inventé.');}
  const eventForm=$('#event-form');if(eventForm){eventForm.elements.date.min=C.today();eventForm.addEventListener('submit',event=>{event.preventDefault();safe(()=>{const v=formData(eventForm);if(!v.title.trim()||!v.location.trim()||!Number.isFinite(C.day(v.date))||C.day(v.date)<C.day(C.today()))throw Error('Indique un titre, un lieu et une date future.');if(new Date(v.date+'T'+v.time).getTime()<=Date.now())throw Error('L’horaire doit être dans le futur.');store.update(s=>s.eventDrafts.push({...v,id:C.uid(),creatorId:'local-device',scope:'local-draft',distance:Number(v.distance),maxParticipants:Number(v.maxParticipants),participants:[],createdAt:new Date().toISOString()}));eventForm.reset();renderEvents();feedback('event-feedback','Brouillon enregistré sur cet appareil. Il n’est pas publié et personne ne peut s’y inscrire.');},'event-feedback');});}
  document.addEventListener('click',event=>{
    const button=event.target.closest('button');if(!button)return;
    for(const [attr,key,render]of [['deleteGoal','goals',renderGoals],['deleteFavorite','favorites',()=>{renderFavorites();renderDashboard();}],['deleteEvent','eventDrafts',renderEvents],['deleteChallenge','challenges',renderChallenges]]){
      if(button.dataset[attr])safe(()=>{store.update(s=>s[key]=s[key].filter(x=>x.id!==button.dataset[attr]));render();},'storage-warning');
    }
    if(button.dataset.deleteActivity)safe(()=>{store.update(s=>{const old=s.activities.find(x=>x.id===button.dataset.deleteActivity);s.activities=s.activities.filter(x=>x.id!==button.dataset.deleteActivity);const w=s.plan?.weeks.flatMap(x=>x.workouts).find(x=>x.id===old?.workoutId);if(w){w.completed=false;w.completedAt=null;}});lists();feedback('activity-feedback','Saisie retirée ; compteurs et séance liée actualisés.');},'activity-feedback');
    if(button.dataset.challenge)safe(()=>{const template=C.templates.find(t=>t.id===button.dataset.challenge);if(!template)return;const month=C.today().slice(0,7),start=month+'-01',end=C.today(new Date(Number(month.slice(0,4)),Number(month.slice(5)),0,12));const id=template.id+'-'+month;store.update(s=>{if(!s.challenges.some(c=>c.id===id))s.challenges.push({...template,id,startDate:start,endDate:end,scope:'personal',reward:null});});renderChallenges();feedback('challenge-feedback','Défi ajouté pour ce mois. Les sorties déjà saisies ce mois-ci sont incluses.');},'challenge-feedback');
  });
  $('#export-data')?.addEventListener('click',()=>safe(()=>{const raw=storage.getItem(store.key);const blob=new Blob([raw||JSON.stringify(store.read(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='run-relais-espace-'+C.today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'storage-warning'));
  $('#confirm-erase')?.addEventListener('change',e=>$('#erase-data').disabled=!e.target.checked);
  $('#erase-data')?.addEventListener('click',()=>{if($('#confirm-erase').checked)safe(()=>{store.clear();location.replace('compte-sportif.html');},'storage-warning');});

  const q=$('#questionnaire-form');
  if(q){
    let step=0,proposal=null;const initial=store.read();fill(q,initial.profile);$('#replace-plan-note').hidden=!initial.plan;
    const dayInputs=[...q.querySelectorAll('[name=trainingDays]')];
    const selectedDays=initial.profile?.trainingDays||({2:[2,6],3:[2,4,0],4:[1,3,5,0],5:[1,2,4,5,0]})[q.elements.sessions.value];
    dayInputs.forEach(input=>input.checked=selectedDays.includes(Number(input.value)));
    function showDayCount(){const count=dayInputs.filter(input=>input.checked).length;$('#training-days-count').textContent=`${count} jour(s) sélectionné(s) sur ${q.elements.sessions.value} à choisir. Espace-les si possible.`;}
    q.addEventListener('change',showDayCount);showDayCount();
    q.elements.targetDate.min=C.addDays(C.today(),1);for(const type of ['input','change'])q.addEventListener(type,()=>{proposal=null;document.getElementById('plan-proposal').replaceChildren();});
    function sportChanged(){const running=q.elements.sport.value==='running';for(const id of ['running-objective','running-baseline','training-days']){const box=document.getElementById(id);box.hidden=!running;for(const input of box.querySelectorAll('input,select'))input.disabled=!running;}$('#other-sport-message').hidden=running;}
    function showStep(){for(const el of q.querySelectorAll('[data-step]'))el.hidden=Number(el.dataset.step)!==step;document.querySelectorAll('.wizard-steps li').forEach((el,i)=>{if(i===step)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});$('#wizard-back').hidden=step===0;$('#wizard-next').hidden=step===2;$('#wizard-generate').hidden=step!==2;const active=q.querySelector(`[data-step="${step}"] legend`);active.tabIndex=-1;active.focus();}
    function validStep(){const active=q.querySelector(`[data-step="${step}"]`);for(const el of active.querySelectorAll('input,select'))if(!el.disabled&&!el.reportValidity())return false;if(step===0&&q.elements.sport.value==='running'&&dayInputs.filter(input=>input.checked).length!==Number(q.elements.sessions.value)){feedback('questionnaire-feedback',`Choisis exactement ${q.elements.sessions.value} jours d’entraînement.`,true);dayInputs[0].focus();return false;}feedback('questionnaire-feedback','');return true;}
    q.elements.sport.addEventListener('change',sportChanged);sportChanged();
    $('#wizard-next').addEventListener('click',()=>{if(validStep()){step++;showStep();}});$('#wizard-back').addEventListener('click',()=>{step--;showStep();});
    q.addEventListener('submit',event=>{event.preventDefault();if(step<2){if(validStep()){step++;showStep();}return;}if(!validStep())return;safe(()=>{
      proposal=C.generate(formData(q));feedback('questionnaire-feedback','');const el=$('#plan-proposal');
      if(proposal.status!=='ready')el.innerHTML=`<div class="sport-empty"><h2>${proposal.status==='unsupported'?'Ce sport arrive plus tard.':'Un objectif à ajuster.'}</h2>${proposal.reasons.map(t=>`<p>${esc(t)}</p>`).join('')}<p>Pas de programme accéléré généré. Tu peux conserver ton profil et revoir l’objectif, ou consulter les PDF et demander un accompagnement adapté.</p><button type="button" class="button" id="save-profile-only">Conserver mon profil local</button><a class="sport-link" href="compte-sportif.html#objectifs">Mes objectifs →</a></div>`;
      else {const p=proposal.plan;el.innerHTML=`<section class="sport-card dark"><span class="sport-tag">PROPOSITION · PAS ENCORE ENREGISTRÉE</span><h2>${esc(C.objectives[p.objective].label)}</h2><p>${p.duration} semaines · ${p.sessionsPerWeek} séances maximum / semaine · objectif le ${date(p.targetDate)}</p>${p.notes.map(n=>`<p>${esc(n)}</p>`).join('')}<h3>Ta première semaine</h3>${p.weeks[0].workouts.map(w=>`<p>${date(w.date)} · ${esc(w.description)}</p>`).join('')}<button type="button" class="button lime" id="adopt-plan">${initial.plan?'Remplacer mon plan actif par cette proposition':'Adopter ce plan sur cet appareil'}</button></section>`;}
      el.focus();el.scrollIntoView({behavior:'smooth',block:'start'});
    },'questionnaire-feedback');});
    $('#plan-proposal').addEventListener('click',event=>safe(()=>{if(event.target.id==='save-profile-only'){store.update(s=>s.profile=proposal.profile);feedback('questionnaire-feedback',savedMessage());}if(event.target.id==='adopt-plan'&&proposal?.status==='ready'){store.update(s=>{s.profile={...s.profile,...proposal.profile};s.plan=proposal.plan;s.goals=s.goals.filter(g=>!g.planId);s.goals.push({id:C.uid(),planId:s.plan.id,sport:'running',title:C.objectives[s.plan.objective].label,date:s.plan.targetDate,distance:Number(s.plan.objective)});});location.href='mon-plan.html';}},'questionnaire-feedback'));
  }
  lists();renderPlan();renderEvents();
})();

